FROM fedora:43

RUN dnf install -y --setopt=install_weak_deps=False \
    ca-certificates openssl-libs \
    && dnf clean all

RUN groupadd -r neon && useradd -r -g neon neon

COPY .docker-staging/storage_controller /usr/local/bin/storage_controller
RUN chmod +x /usr/local/bin/storage_controller

USER neon

EXPOSE 6060 9898

ENTRYPOINT ["storage_controller"]
